spring.application.name=astra-tarot-web-be
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/astra_tarot
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.jdbc=${JDBC_LOG_LEVEL:WARN}
# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.open-in-view=false

# Server
server.port=8080

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:900000}

# App
app.frontend-url=${FRONTEND_URL:http://localhost:3000}

# OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.provider.google.user-name-attribute=sub

app.mail.from-email=${MAIL_FROM_EMAIL:astratarot.noreply@gmail.com}
app.mail.from-name=${MAIL_FROM_NAME:Astra Tarot}

# Mail
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS}