-- ============================================================
-- READER APPLICATION & ADMIN ACCOUNT
-- ============================================================

-- TABLE: reader_applications
-- Stores applications from users wanting to become professional readers
CREATE TABLE reader_applications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bio TEXT NOT NULL,
    experience INTEGER DEFAULT 0 CHECK (experience >= 0),
    specialties TEXT[] DEFAULT '{}',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    reviewed_by UUID REFERENCES users(id),
    reviewed_at TIMESTAMPTZ,
    rejection_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_reader_app_user ON reader_applications(user_id);
CREATE INDEX idx_reader_app_status ON reader_applications(status);

CREATE TRIGGER trg_reader_apps BEFORE UPDATE ON reader_applications
FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ============================================================
-- ADMIN USER SEED
-- ============================================================
-- Insert a default admin account (password: admin123)
-- Hash generated by BCryptPasswordEncoder with default strength (10)
INSERT INTO users (
    id,
    username,
    email,
    password_hash,
    full_name,
    role,
    status,
    email_verified,
    auth_provider,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(),
    'admin',
    'admin@example.com',
    '$2a$10$blHfFtzwiJo6RwZUueJ1AOJKbVrXfIWNhsebN9gKESfQB/rvgRpOa',
    'Admin User',
    'ADMIN',
    'ACTIVE',
    TRUE,
    'LOCAL',
    NOW(),
    NOW()
) ON CONFLICT (username) DO NOTHING;
