INSERT INTO tarot_cards (name, arcana_type, card_number, image_url) VALUES

-- Major Arcana
('The Fool','Major Arcana',0,NULL),
('The Magician','Major Arcana',1,NULL),
('The High Priestess','Major Arcana',2,NULL),
('The Empress','Major Arcana',3,NULL),
('The Emperor','Major Arcana',4,NULL),
('The Hierophant','Major Arcana',5,NULL),
('The Lovers','Major Arcana',6,NULL),
('The Chariot','Major Arcana',7,NULL),
('Strength','Major Arcana',8,NULL),
('The Hermit','Major Arcana',9,NULL),
('Wheel of Fortune','Major Arcana',10,NULL),
('Justice','Major Arcana',11,NULL),
('The Hanged Man','Major Arcana',12,NULL),
('Death','Major Arcana',13,NULL),
('Temperance','Major Arcana',14,NULL),
('The Devil','Major Arcana',15,NULL),
('The Tower','Major Arcana',16,NULL),
('The Star','Major Arcana',17,NULL),
('The Moon','Major Arcana',18,NULL),
('The Sun','Major Arcana',19,NULL),
('Judgement','Major Arcana',20,NULL),
('The World','Major Arcana',21,NULL),

-- Wands
('Ace of Wands','Wands',1,NULL),
('Two of Wands','Wands',2,NULL),
('Three of Wands','Wands',3,NULL),
('Four of Wands','Wands',4,NULL),
('Five of Wands','Wands',5,NULL),
('Six of Wands','Wands',6,NULL),
('Seven of Wands','Wands',7,NULL),
('Eight of Wands','Wands',8,NULL),
('Nine of Wands','Wands',9,NULL),
('Ten of Wands','Wands',10,NULL),
('Page of Wands','Wands',11,NULL),
('Knight of Wands','Wands',12,NULL),
('Queen of Wands','Wands',13,NULL),
('King of Wands','Wands',14,NULL),

-- Cups
('Ace of Cups','Cups',1,NULL),
('Two of Cups','Cups',2,NULL),
('Three of Cups','Cups',3,NULL),
('Four of Cups','Cups',4,NULL),
('Five of Cups','Cups',5,NULL),
('Six of Cups','Cups',6,NULL),
('Seven of Cups','Cups',7,NULL),
('Eight of Cups','Cups',8,NULL),
('Nine of Cups','Cups',9,NULL),
('Ten of Cups','Cups',10,NULL),
('Page of Cups','Cups',11,NULL),
('Knight of Cups','Cups',12,NULL),
('Queen of Cups','Cups',13,NULL),
('King of Cups','Cups',14,NULL),

-- Swords
('Ace of Swords','Swords',1,NULL),
('Two of Swords','Swords',2,NULL),
('Three of Swords','Swords',3,NULL),
('Four of Swords','Swords',4,NULL),
('Five of Swords','Swords',5,NULL),
('Six of Swords','Swords',6,NULL),
('Seven of Swords','Swords',7,NULL),
('Eight of Swords','Swords',8,NULL),
('Nine of Swords','Swords',9,NULL),
('Ten of Swords','Swords',10,NULL),
('Page of Swords','Swords',11,NULL),
('Knight of Swords','Swords',12,NULL),
('Queen of Swords','Swords',13,NULL),
('King of Swords','Swords',14,NULL),

-- Pentacles
('Ace of Pentacles','Pentacles',1,NULL),
('Two of Pentacles','Pentacles',2,NULL),
('Three of Pentacles','Pentacles',3,NULL),
('Four of Pentacles','Pentacles',4,NULL),
('Five of Pentacles','Pentacles',5,NULL),
('Six of Pentacles','Pentacles',6,NULL),
('Seven of Pentacles','Pentacles',7,NULL),
('Eight of Pentacles','Pentacles',8,NULL),
('Nine of Pentacles','Pentacles',9,NULL),
('Ten of Pentacles','Pentacles',10,NULL),
('Page of Pentacles','Pentacles',11,NULL),
('Knight of Pentacles','Pentacles',12,NULL),
('Queen of Pentacles','Pentacles',13,NULL),
('King of Pentacles','Pentacles',14,NULL);